<?php declare(strict_types=1);

/**
 * @author Siteation (https://siteation.dev/)
 * @copyright Copyright 2021 Siteation (https://siteation.dev/)
 * @license MIT
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */
?>

<?= $secureRenderer->renderTag('script', [], <<<script
    window.addEventListener('pageshow', (event) => {
        if (event.persisted) {
            require(['Magento_Customer/js/customer-data'], function (customerData) {
                const sections = ['cart'];
                customerData.invalidate(sections);
                customerData.reload(sections, true);
            });
        };
    });
script, false); ?>
