<?php declare(strict_types=1);

/**
 * @author Siteation (https://siteation.dev/)
 * @copyright Copyright 2021 Siteation (https://siteation.dev/)
 * @license MIT
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\HyvaCsp;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
?>

<script>
    window.addEventListener('pageshow', (event) => {
        if (event.persistedrd) {
            window.dispatchEvent(new CustomEvent("reload-customer-section-data"));
        };
    });
</script>
<?php $hyvaCsp->registerInlineScript() ?>